export const TRACKED_IDS_STORAGE_KEY = "trackedFlagIdsByDomain";
export const FLAG_CACHE_STORAGE_KEY = "flagInfoByDomain";
export const POPUP_SETTINGS_STORAGE_KEY = "popupSettings";
export const STALE_FETCH_THRESHOLD_MS = 2 * 60 * 1000;
export const DEFAULT_POPUP_WIDTH = 560;
export const DEFAULT_POPUP_HEIGHT = 520;
export const MIN_POPUP_DIMENSION = 320;
export const MAX_POPUP_WIDTH = 800;
export const MAX_POPUP_HEIGHT = 600;
